// src/features/analytics/services/getSampleData.ts
import { Activity, ActivityType } from '@prisma/client';
import { DailyStats, PatternData, WeeklyStat, PredictedActivityPatterns } from '@/shared/types/schemas';

// Helper function to create a date relative to today
const getRelativeDate = (dayOffset: number, hour: number, minute: number): Date => {
  const date = new Date();
  date.setDate(date.getDate() + dayOffset);
  date.setHours(hour, minute, 0, 0);
  return date;
};

// 1. Sample Activities
export const getSampleActivities = (date: Date): Activity[] => {
  const dayOffset = Math.floor((date.getTime() - new Date().setHours(0, 0, 0, 0)) / (1000 * 60 * 60 * 24));
  const datePrefix = date.toISOString().split('T')[0];
  
  const activities: Activity[] = [
    // 밤 수면 (전날 밤 ~ 아침)
    {
      id: `${datePrefix}-sample-sleep-night`,
      babyId: 'guest-baby-id',
      userId: 'guest-user-id',
      type: ActivityType.SLEEP,
      startTime: getRelativeDate(dayOffset - 1, 22, 30),
      endTime: getRelativeDate(dayOffset, 6, 15),
      memo: '밤잠',
      feedingType: null,
      feedingAmount: null,
      breastSide: null,
      sleepType: 'NIGHT',
      duration: 465,
      diaperType: null,
            bathType: null,
      bathTemp: null,
      playType: null,
      playDuration: null,
      medicineName: null,
      medicineAmount: null,
      medicineUnit: null,
      stoolCondition: null,
      temperature: null,
      reaction: null,
      playLocation: null,
      createdAt: getRelativeDate(dayOffset - 1, 22, 30),
      updatedAt: getRelativeDate(dayOffset - 1, 22, 30),
      originalActivityId: null,
      isSplit: false,
      splitSequence: null,    },
    // 아침 수유 #1
    {
      id: `${datePrefix}-sample-feeding-1`,
      babyId: 'guest-baby-id',
      userId: 'guest-user-id',
      type: ActivityType.FEEDING,
      startTime: getRelativeDate(dayOffset, 6, 30),
      endTime: null,
      memo: null,
      feedingType: 'breast',
      feedingAmount: null,
      breastSide: 'left',
      sleepType: null,
      duration: 15,
      diaperType: null,
            bathType: null,
      bathTemp: null,
      playType: null,
      playDuration: null,
      medicineName: null,
      medicineAmount: null,
      medicineUnit: null,
      stoolCondition: null,
      temperature: null,
      reaction: null,
      playLocation: null,
      createdAt: getRelativeDate(dayOffset, 6, 30),
      updatedAt: getRelativeDate(dayOffset, 6, 30),
      originalActivityId: null,
      isSplit: false,
      splitSequence: null,    },
    // 배변 #1
    {
      id: `${datePrefix}-sample-diaper-1`,
      babyId: 'guest-baby-id',
      userId: 'guest-user-id',
      type: ActivityType.DIAPER,
      startTime: getRelativeDate(dayOffset, 7, 0),
      endTime: null,
      memo: null,
      feedingType: null,
      feedingAmount: null,
      breastSide: null,
      sleepType: null,
      duration: null,
      diaperType: 'urine',
            bathType: null,
      bathTemp: null,
      playType: null,
      playDuration: null,
      medicineName: null,
      medicineAmount: null,
      medicineUnit: null,
      stoolCondition: null,
      temperature: null,
      reaction: null,
      playLocation: null,
      createdAt: getRelativeDate(dayOffset, 7, 0),
      updatedAt: getRelativeDate(dayOffset, 7, 0),
      originalActivityId: null,
      isSplit: false,
      splitSequence: null,    },
    // 오전 낮잠 #1
    {
      id: `${datePrefix}-sample-sleep-1`,
      babyId: 'guest-baby-id',
      userId: 'guest-user-id',
      type: ActivityType.SLEEP,
      startTime: getRelativeDate(dayOffset, 8, 0),
      endTime: getRelativeDate(dayOffset, 9, 30),
      memo: null,
      feedingType: null,
      feedingAmount: null,
      breastSide: null,
      sleepType: 'nap',
      duration: 90,
      diaperType: null,
            bathType: null,
      bathTemp: null,
      playType: null,
      playDuration: null,
      medicineName: null,
      medicineAmount: null,
      medicineUnit: null,
      stoolCondition: null,
      temperature: null,
      reaction: null,
      playLocation: null,
      createdAt: getRelativeDate(dayOffset, 8, 0),
      updatedAt: getRelativeDate(dayOffset, 8, 0),
      originalActivityId: null,
      isSplit: false,
      splitSequence: null,    },
    // 수유 #2
    {
      id: `${datePrefix}-sample-feeding-2`,
      babyId: 'guest-baby-id',
      userId: 'guest-user-id',
      type: ActivityType.FEEDING,
      startTime: getRelativeDate(dayOffset, 10, 0),
      endTime: null,
      memo: null,
      feedingType: 'formula',
      feedingAmount: 120,
      breastSide: null,
      sleepType: null,
      duration: null,
      diaperType: null,
            bathType: null,
      bathTemp: null,
      playType: null,
      playDuration: null,
      medicineName: null,
      medicineAmount: null,
      medicineUnit: null,
      stoolCondition: null,
      temperature: null,
      reaction: null,
      playLocation: null,
      createdAt: getRelativeDate(dayOffset, 10, 0),
      updatedAt: getRelativeDate(dayOffset, 10, 0),
      originalActivityId: null,
      isSplit: false,
      splitSequence: null,    },
    // 배변 #2
    {
      id: `${datePrefix}-sample-diaper-2`,
      babyId: 'guest-baby-id',
      userId: 'guest-user-id',
      type: ActivityType.DIAPER,
      startTime: getRelativeDate(dayOffset, 10, 45),
      endTime: null,
      memo: null,
      feedingType: null,
      feedingAmount: null,
      breastSide: null,
      sleepType: null,
      duration: null,
      diaperType: 'stool',
            bathType: null,
      bathTemp: null,
      playType: null,
      playDuration: null,
      medicineName: null,
      medicineAmount: null,
      medicineUnit: null,
      stoolCondition: null,
      temperature: null,
      reaction: null,
      playLocation: null,
      createdAt: getRelativeDate(dayOffset, 10, 45),
      updatedAt: getRelativeDate(dayOffset, 10, 45),
      originalActivityId: null,
      isSplit: false,
      splitSequence: null,    },
    // 낮잠 #2
    {
      id: `${datePrefix}-sample-sleep-2`,
      babyId: 'guest-baby-id',
      userId: 'guest-user-id',
      type: ActivityType.SLEEP,
      startTime: getRelativeDate(dayOffset, 12, 0),
      endTime: getRelativeDate(dayOffset, 13, 15),
      memo: null,
      feedingType: null,
      feedingAmount: null,
      breastSide: null,
      sleepType: 'nap',
      duration: 75,
      diaperType: null,
            bathType: null,
      bathTemp: null,
      playType: null,
      playDuration: null,
      medicineName: null,
      medicineAmount: null,
      medicineUnit: null,
      stoolCondition: null,
      temperature: null,
      reaction: null,
      playLocation: null,
      createdAt: getRelativeDate(dayOffset, 12, 0),
      updatedAt: getRelativeDate(dayOffset, 12, 0),
      originalActivityId: null,
      isSplit: false,
      splitSequence: null,    },
    // 수유 #3
    {
      id: `${datePrefix}-sample-feeding-3`,
      babyId: 'guest-baby-id',
      userId: 'guest-user-id',
      type: ActivityType.FEEDING,
      startTime: getRelativeDate(dayOffset, 13, 30),
      endTime: null,
      memo: null,
      feedingType: 'baby_food',
      feedingAmount: 80,
      breastSide: null,
      sleepType: null,
      duration: null,
      diaperType: null,
            bathType: null,
      bathTemp: null,
      playType: null,
      playDuration: null,
      medicineName: null,
      medicineAmount: null,
      medicineUnit: null,
      stoolCondition: null,
      temperature: null,
      reaction: null,
      playLocation: null,
      createdAt: getRelativeDate(dayOffset, 13, 30),
      updatedAt: getRelativeDate(dayOffset, 13, 30),
      originalActivityId: null,
      isSplit: false,
      splitSequence: null,    },
    // 배변 #3
    {
      id: `${datePrefix}-sample-diaper-3`,
      babyId: 'guest-baby-id',
      userId: 'guest-user-id',
      type: ActivityType.DIAPER,
      startTime: getRelativeDate(dayOffset, 14, 15),
      endTime: null,
      memo: null,
      feedingType: null,
      feedingAmount: null,
      breastSide: null,
      sleepType: null,
      duration: null,
      diaperType: 'urine',
            bathType: null,
      bathTemp: null,
      playType: null,
      playDuration: null,
      medicineName: null,
      medicineAmount: null,
      medicineUnit: null,
      stoolCondition: null,
      temperature: null,
      reaction: null,
      playLocation: null,
      createdAt: getRelativeDate(dayOffset, 14, 15),
      updatedAt: getRelativeDate(dayOffset, 14, 15),
      originalActivityId: null,
      isSplit: false,
      splitSequence: null,    },
    // 체온 측정
    {
      id: `${datePrefix}-sample-temp-1`,
      babyId: 'guest-baby-id',
      userId: 'guest-user-id',
      type: ActivityType.TEMPERATURE,
      startTime: getRelativeDate(dayOffset, 15, 0),
      endTime: null,
      memo: '정상',
      feedingType: null,
      feedingAmount: null,
      breastSide: null,
      sleepType: null,
      duration: null,
      diaperType: null,
            bathType: null,
      bathTemp: null,
      playType: null,
      playDuration: null,
      medicineName: null,
      medicineAmount: null,
      medicineUnit: null,
      temperature: 36.8,
      stoolCondition: null,
      reaction: null,
      playLocation: null,
      createdAt: getRelativeDate(dayOffset, 15, 0),
      updatedAt: getRelativeDate(dayOffset, 15, 0),
      originalActivityId: null,
      isSplit: false,
      splitSequence: null,    },
    // 낮잠 #3
    {
      id: `${datePrefix}-sample-sleep-3`,
      babyId: 'guest-baby-id',
      userId: 'guest-user-id',
      type: ActivityType.SLEEP,
      startTime: getRelativeDate(dayOffset, 15, 30),
      endTime: getRelativeDate(dayOffset, 16, 45),
      memo: null,
      feedingType: null,
      feedingAmount: null,
      breastSide: null,
      sleepType: 'nap',
      duration: 75,
      diaperType: null,
            bathType: null,
      bathTemp: null,
      playType: null,
      playDuration: null,
      medicineName: null,
      medicineAmount: null,
      medicineUnit: null,
      stoolCondition: null,
      temperature: null,
      reaction: null,
      playLocation: null,
      createdAt: getRelativeDate(dayOffset, 15, 30),
      updatedAt: getRelativeDate(dayOffset, 15, 30),
      originalActivityId: null,
      isSplit: false,
      splitSequence: null,    },
    // 수유 #4
    {
      id: `${datePrefix}-sample-feeding-4`,
      babyId: 'guest-baby-id',
      userId: 'guest-user-id',
      type: ActivityType.FEEDING,
      startTime: getRelativeDate(dayOffset, 17, 0),
      endTime: null,
      memo: null,
      feedingType: 'breast',
      feedingAmount: null,
      breastSide: 'right',
      sleepType: null,
      duration: 20,
      diaperType: null,
            bathType: null,
      bathTemp: null,
      playType: null,
      playDuration: null,
      medicineName: null,
      medicineAmount: null,
      medicineUnit: null,
      stoolCondition: null,
      temperature: null,
      reaction: null,
      playLocation: null,
      createdAt: getRelativeDate(dayOffset, 17, 0),
      updatedAt: getRelativeDate(dayOffset, 17, 0),
      originalActivityId: null,
      isSplit: false,
      splitSequence: null,    },
    // 배변 #4
    {
      id: `${datePrefix}-sample-diaper-4`,
      babyId: 'guest-baby-id',
      userId: 'guest-user-id',
      type: ActivityType.DIAPER,
      startTime: getRelativeDate(dayOffset, 17, 45),
      endTime: null,
      memo: null,
      feedingType: null,
      feedingAmount: null,
      breastSide: null,
      sleepType: null,
      duration: null,
      diaperType: 'urine',
            bathType: null,
      bathTemp: null,
      playType: null,
      playDuration: null,
      medicineName: null,
      medicineAmount: null,
      medicineUnit: null,
      stoolCondition: null,
      temperature: null,
      reaction: null,
      playLocation: null,
      createdAt: getRelativeDate(dayOffset, 17, 45),
      updatedAt: getRelativeDate(dayOffset, 17, 45),
      originalActivityId: null,
      isSplit: false,
      splitSequence: null,    },
    // 수유 #5
    {
      id: `${datePrefix}-sample-feeding-5`,
      babyId: 'guest-baby-id',
      userId: 'guest-user-id',
      type: ActivityType.FEEDING,
      startTime: getRelativeDate(dayOffset, 19, 30),
      endTime: null,
      memo: null,
      feedingType: 'formula',
      feedingAmount: 150,
      breastSide: null,
      sleepType: null,
      duration: null,
      diaperType: null,
            bathType: null,
      bathTemp: null,
      playType: null,
      playDuration: null,
      medicineName: null,
      medicineAmount: null,
      medicineUnit: null,
      stoolCondition: null,
      temperature: null,
      reaction: null,
      playLocation: null,
      createdAt: getRelativeDate(dayOffset, 19, 30),
      updatedAt: getRelativeDate(dayOffset, 19, 30),
      originalActivityId: null,
      isSplit: false,
      splitSequence: null,    },
    // 배변 #5
    {
      id: `${datePrefix}-sample-diaper-5`,
      babyId: 'guest-baby-id',
      userId: 'guest-user-id',
      type: ActivityType.DIAPER,
      startTime: getRelativeDate(dayOffset, 20, 15),
      endTime: null,
      memo: null,
      feedingType: null,
      feedingAmount: null,
      breastSide: null,
      sleepType: null,
      duration: null,
      diaperType: 'stool',
            bathType: null,
      bathTemp: null,
      playType: null,
      playDuration: null,
      medicineName: null,
      medicineAmount: null,
      medicineUnit: null,
      stoolCondition: null,
      temperature: null,
      reaction: null,
      playLocation: null,
      createdAt: getRelativeDate(dayOffset, 20, 15),
      updatedAt: getRelativeDate(dayOffset, 20, 15),
      originalActivityId: null,
      isSplit: false,
      splitSequence: null,    },
    // 약 복용
    {
      id: `${datePrefix}-sample-medicine-1`,
      babyId: 'guest-baby-id',
      userId: 'guest-user-id',
      type: ActivityType.MEDICINE,
      startTime: getRelativeDate(dayOffset, 21, 0),
      endTime: null,
      memo: null,
      feedingType: null,
      feedingAmount: null,
      breastSide: null,
      sleepType: null,
      duration: null,
      diaperType: null,
            bathType: null,
      bathTemp: null,
      playType: null,
      playDuration: null,
      medicineName: '아세트아미노펜',
      medicineAmount: '2.5',
      medicineUnit: 'ml',
      stoolCondition: null,
      temperature: null,
      reaction: null,
      playLocation: null,
      createdAt: getRelativeDate(dayOffset, 21, 0),
      updatedAt: getRelativeDate(dayOffset, 21, 0),
      originalActivityId: null,
      isSplit: false,
      splitSequence: null,    },
    // 수유 #6 (밤 수유)
    {
      id: `${datePrefix}-sample-feeding-6`,
      babyId: 'guest-baby-id',
      userId: 'guest-user-id',
      type: ActivityType.FEEDING,
      startTime: getRelativeDate(dayOffset, 22, 0),
      endTime: null,
      memo: null,
      feedingType: 'breast',
      feedingAmount: null,
      breastSide: 'left',
      sleepType: null,
      duration: 18,
      diaperType: null,
            bathType: null,
      bathTemp: null,
      playType: null,
      playDuration: null,
      medicineName: null,
      medicineAmount: null,
      medicineUnit: null,
      stoolCondition: null,
      temperature: null,
      reaction: null,
      playLocation: null,
      createdAt: getRelativeDate(dayOffset, 22, 0),
      updatedAt: getRelativeDate(dayOffset, 22, 0),
      originalActivityId: null,
      isSplit: false,
      splitSequence: null,    },
  ];
  return activities;
};

// 2. Sample Daily Stats
export const getSampleDailyStats = (): DailyStats => ({
  feeding: { count: 8, totalAmount: 980, avgAmount: 122 },
  sleep: { count: 5, totalHours: 14.5 },
  diaper: { urine: 7, stool: 3 },
});

// 3. Sample 24-Hour Pattern
export const getSample24HourPattern = (): PatternData[] => {
    const now = new Date();
    const pattern: PatternData[] = [];
    for (let i = 23; i >= 0; i--) {
      const hour = (now.getHours() - i + 24) % 24;
      pattern.push({
        hour: `${hour}:00`,
        [ActivityType.FEEDING]: Math.random() > 0.7 ? Math.floor(Math.random() * 3) + 1 : 0,
        [ActivityType.SLEEP]: Math.random() > 0.5 ? Math.floor(Math.random() * 2) + 1 : 0,
        [ActivityType.DIAPER]: Math.random() > 0.6 ? Math.floor(Math.random() * 3) + 1 : 0,
      });
    }
    return pattern;
  };

// 4. Sample Weekly Stats
export const getSampleWeeklyStats = (): WeeklyStat[] => {
  const weeklyStats: WeeklyStat[] = [];
  for (let i = 6; i >= 0; i--) {
    const date = new Date();
    date.setDate(date.getDate() - i);
    weeklyStats.push({
      date: date.toISOString().split('T')[0],
      totalFeeding: Math.floor(900 + Math.random() * 150),
      totalSleep: parseFloat((13 + Math.random() * 3).toFixed(1)),
    });
  }
  return weeklyStats;
};

// 5. Sample Predicted Patterns
export const getSamplePredictedPatterns = (): PredictedActivityPatterns => {
    const now = new Date();
    return {
      [ActivityType.FEEDING]: {
        nextTime: new Date(now.getTime() + 60 * 60 * 1000),
        confidence: 0.85,
        avgInterval: 180,
        avgAmount: 130,
      },
      [ActivityType.SLEEP]: {
        nextTime: new Date(now.getTime() + 90 * 60 * 1000),
        confidence: 0.78,
        avgInterval: 240,
        avgDuration: 90,
      },
      [ActivityType.DIAPER]: {
        nextTime: new Date(now.getTime() + 45 * 60 * 1000),
        confidence: 0.9,
        avgInterval: 150,
      },
    };
  };
